sudo: required
language : 
  - go  
os:
  - linux
services:
  - docker

branches:
  only:
    - master
    - /^v\d+\.\d+\.\d+(\.\d+)?(-\S*)?$/
    - chore-mashling-version-update
    
cache:
  bundler: false
  directories:
  - .build-cache          # images.txt
# Handle git submodules yourself
git:
    submodules: false
# Do a github login using token
before_install:
  - "echo -e \"machine github.com\n  login ${GITHUB_USER_TOKEN}\" >> ~/.netrc"
install:
  - go get -u github.com/constabulary/gb/...
  - go get -u github.com/tools/godep/... 
  
  
script:
  - cd $GOPATH/src/github.com/TIBCOSoftware
  - git clone https://github.com/TIBCOSoftware/mashling-cicd.git mashling-cicd
  - cp -r $GOPATH/src/github.com/TIBCOSoftware/mashling-cicd/dependency-config/* $GOPATH/src/github.com/TIBCOSoftware/mashling
  - cd mashling
  - git status
  - godep restore
  #- go test ./...
  - go install ./...
  - git status
  - make all
  - mashling help
  
