
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"


[[constraint]]
  name = "github.com/NodePrime/jsonpath"
  version = "0.3.1"

[[constraint]]
  name = "github.com/Shopify/sarama"
  version = "1.12.0"

[[constraint]]
  name = "github.com/TIBCOSoftware/flogo-cli"
  branch = "master"

[[constraint]]
  name = "github.com/TIBCOSoftware/flogo-contrib"
  branch = "master"

[[constraint]]
  name = "github.com/TIBCOSoftware/flogo-lib"
  branch = "master"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.5.0"

[[constraint]]
  name = "github.com/lightstep/lightstep-tracer-go"
  version = "0.14.0"

[[constraint]]
  name = "github.com/opentracing/opentracing-go"
  version = "1.0.2"

[[constraint]]
  name = "github.com/openzipkin/zipkin-go-opentracing"
  version = "0.3.1"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.1.4"

[[constraint]]
  branch = "master"
  name = "github.com/xeipuuv/gojsonschema"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[[constraint]]
  branch = "master"
  name = "sourcegraph.com/sourcegraph/appdash"
